# Form implementation generated from reading ui file 'e:\Documentos\Proyectos\Python\Proyecto1\gui\login.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_formLogin(object):
    def setupUi(self, formLogin):
        formLogin.setObjectName("formLogin")
        formLogin.resize(400, 342)
        formLogin.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.label = QtWidgets.QLabel(parent=formLogin)
        self.label.setGeometry(QtCore.QRect(120, 30, 171, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("e:\\Documentos\\Proyectos\\Python\\Proyecto1\\gui\\logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=formLogin)
        self.label_2.setGeometry(QtCore.QRect(150, 110, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=formLogin)
        self.label_3.setGeometry(QtCore.QRect(30, 160, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=formLogin)
        self.label_4.setGeometry(QtCore.QRect(30, 210, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txtUsuario = QtWidgets.QLineEdit(parent=formLogin)
        self.txtUsuario.setGeometry(QtCore.QRect(130, 150, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtUsuario.setFont(font)
        self.txtUsuario.setStyleSheet("border:solid 1px;\n"
"border-radius:8px;")
        self.txtUsuario.setObjectName("txtUsuario")
        self.txtClave = QtWidgets.QLineEdit(parent=formLogin)
        self.txtClave.setGeometry(QtCore.QRect(130, 200, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtClave.setFont(font)
        self.txtClave.setStyleSheet("")
        self.txtClave.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtClave.setObjectName("txtClave")
        self.btnAcceder = QtWidgets.QPushButton(parent=formLogin)
        self.btnAcceder.setGeometry(QtCore.QRect(140, 250, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnAcceder.setFont(font)
        self.btnAcceder.setStyleSheet("background-color: rgb(255, 105, 3);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px")
        self.btnAcceder.setObjectName("btnAcceder")
        self.lblMensaje = QtWidgets.QLabel(parent=formLogin)
        self.lblMensaje.setGeometry(QtCore.QRect(48, 300, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblMensaje.setFont(font)
        self.lblMensaje.setStyleSheet("color: rgb(255, 0, 0);")
        self.lblMensaje.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblMensaje.setObjectName("lblMensaje")

        self.retranslateUi(formLogin)
        QtCore.QMetaObject.connectSlotsByName(formLogin)

    def retranslateUi(self, formLogin):
        _translate = QtCore.QCoreApplication.translate
        formLogin.setWindowTitle(_translate("formLogin", "Inicio de sesión"))
        self.label_2.setText(_translate("formLogin", "Inicio de sesíon"))
        self.label_3.setText(_translate("formLogin", "Usuario:"))
        self.label_4.setText(_translate("formLogin", "Contraseña:"))
        self.txtUsuario.setText(_translate("formLogin", "admin"))
        self.txtUsuario.setPlaceholderText(_translate("formLogin", "Ingrese su usuario"))
        self.txtClave.setText(_translate("formLogin", "admin2050."))
        self.txtClave.setPlaceholderText(_translate("formLogin", "Ingrese su contraseña"))
        self.btnAcceder.setText(_translate("formLogin", "Acceder"))
        self.lblMensaje.setText(_translate("formLogin", "mensaje"))
