# Form implementation generated from reading ui file 'e:\Documentos\Proyectos\Python\Proyecto1\gui\main.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=main)
        self.centralwidget.setObjectName("centralwidget")
        main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuArchivos = QtWidgets.QMenu(parent=self.menubar)
        self.menuArchivos.setObjectName("menuArchivos")
        self.menuCreditos = QtWidgets.QMenu(parent=self.menubar)
        self.menuCreditos.setObjectName("menuCreditos")
        main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=main)
        self.statusbar.setObjectName("statusbar")
        main.setStatusBar(self.statusbar)
        self.actionDesarrolladores = QtGui.QAction(parent=main)
        self.actionDesarrolladores.setObjectName("actionDesarrolladores")
        self.btnRegistrarTransferencias = QtGui.QAction(parent=main)
        self.btnRegistrarTransferencias.setObjectName("btnRegistrarTransferencias")
        self.btnReportarTransferencia = QtGui.QAction(parent=main)
        self.btnReportarTransferencia.setObjectName("btnReportarTransferencia")
        self.btnHistorialTransferencias = QtGui.QAction(parent=main)
        self.btnHistorialTransferencias.setObjectName("btnHistorialTransferencias")
        self.menuArchivos.addAction(self.btnRegistrarTransferencias)
        self.menuArchivos.addAction(self.btnReportarTransferencia)
        self.menuArchivos.addAction(self.btnHistorialTransferencias)
        self.menuCreditos.addAction(self.actionDesarrolladores)
        self.menubar.addAction(self.menuArchivos.menuAction())
        self.menubar.addAction(self.menuCreditos.menuAction())

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "CompanyName - Transferencias"))
        self.menuArchivos.setTitle(_translate("main", "Archivos"))
        self.menuCreditos.setTitle(_translate("main", "Créditos"))
        self.actionDesarrolladores.setText(_translate("main", "Desarrolladores"))
        self.btnRegistrarTransferencias.setText(_translate("main", "Registrar Transferencias"))
        self.btnRegistrarTransferencias.setShortcut(_translate("main", "Ctrl+R"))
        self.btnReportarTransferencia.setText(_translate("main", "Reportar Transferencia"))
        self.btnReportarTransferencia.setShortcut(_translate("main", "Ctrl+T"))
        self.btnHistorialTransferencias.setText(_translate("main", "Historial de Transferencias"))
        self.btnHistorialTransferencias.setShortcut(_translate("main", "Ctrl+B"))
